// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAudg0PssANvG4taMY8Nnb_Jwq6KkO8XGo',
    appId: '1:348331404457:web:2c4a82a8f5861c9cd60db8',
    messagingSenderId: '348331404457',
    projectId: 'newsfiy-app',
    authDomain: 'newsfiy-app.firebaseapp.com',
    storageBucket: 'newsfiy-app.firebasestorage.app',
    measurementId: 'G-YWK3MD4E6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc_d9h_ZMQSsXxBdDm6TursPBLZYXhQQc',
    appId: '1:348331404457:android:e907ea9f03469a2ed60db8',
    messagingSenderId: '348331404457',
    projectId: 'newsfiy-app',
    storageBucket: 'newsfiy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwkr0c6MV5XWknj40QM7txiq9lORcvPhg',
    appId: '1:348331404457:ios:abb78d1f4a14f5a9d60db8',
    messagingSenderId: '348331404457',
    projectId: 'newsfiy-app',
    storageBucket: 'newsfiy-app.firebasestorage.app',
    iosBundleId: 'com.example.newsify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwkr0c6MV5XWknj40QM7txiq9lORcvPhg',
    appId: '1:348331404457:ios:abb78d1f4a14f5a9d60db8',
    messagingSenderId: '348331404457',
    projectId: 'newsfiy-app',
    storageBucket: 'newsfiy-app.firebasestorage.app',
    iosBundleId: 'com.example.newsify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAudg0PssANvG4taMY8Nnb_Jwq6KkO8XGo',
    appId: '1:348331404457:web:2d7c75f43b42f472d60db8',
    messagingSenderId: '348331404457',
    projectId: 'newsfiy-app',
    authDomain: 'newsfiy-app.firebaseapp.com',
    storageBucket: 'newsfiy-app.firebasestorage.app',
    measurementId: 'G-HT21EGLY42',
  );
}
